# -*- coding: utf-8 -*-
"""mô hình nhận diện khuôn mặt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKCGORxaXEp2BgRBx4p2xCt__r03smMP
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

# 1. TIỀN XỬ LÝ DỮ LIỆU
# Thiết lập đường dẫn dữ liệu
train_dir = "/content/drive/MyDrive/Ảnh selfie cho chiều t2 18 5"

# Kích thước ảnh và kích thước lô
img_width, img_height = 128, 128
batch_size = 32

# Tăng cường dữ liệu dành cho huấn luyện mô hình
train_datagen = ImageDataGenerator(
    rescale=1.0/255, # Normalize pixel values
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode="nearest"
)
# Tải dữ liệu huấn luyện
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="categorical"
)

# XÂY DỰNG MÔ HÌNH CNN
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(img_width, img_height, 3)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Conv2D(128, (3,3), activation="relu"),
    MaxPooling2D(2,2),
    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5), # Reduce overfitting
    Dense(37, activation="softmax") # 5 categories
])
# Biên dịch mô hình
model.compile(optimizer="adam",
              loss="categorical_crossentropy",
              metrics=["accuracy"])

# Tóm tắt cấu hình của mô hình
model.summary()

# HUẤN LUYÊN MÔ HÌNH CNN
epochs = 50
history = model.fit(train_generator, epochs=epochs)

# ĐÁNH GIÁ KẾT QUẢ MÔ HÌNH
plt.plot(history.history['accuracy'], label="Kết quả huấn luyện")
# plt.plot(history.history['val_accuracy'], label="Độ chính xác xác thực") # Removed as val_accuracy is not available without validation_data
plt.xlabel("Số lần học")
plt.ylabel("Độ chính xác")
plt.legend()
plt.show()
#lưu mô hình
model.save('mô hình nhận diện.h5')
with open("class_indices_cnn.json", "w") as f:
    json.dump(train_generator.class_indices, f)

!pip install mtcnn opencv-python tensorflow -q
!pip install --upgrade h5py
import cv2
import json
import numpy as np
import matplotlib.pyplot as plt
from mtcnn import MTCNN
from keras.models import load_model
from keras.preprocessing.image import img_to_array
import h5py


# Thử mở file bằng h5py trước để kiểm tra tính toàn vẹn
try:
    with h5py.File('/content/mô hình nhận diện.h5', 'r') as f:
        print("File mở thành công bằng h5py!")
        # Nếu mở được, dùng lệnh load_model
        model = load_model("/content/mô hình nhận diện.h5")
except Exception as e:
    print(f"Lỗi khi mở file: {e}")


# ============================================================
# 2. LOAD LABEL
# ============================================================

with open("class_indices_cnn.json", "r") as f:

    class_indices = json.load(f)

# Đảo ngược dictionary
labels = {v:k for k,v in class_indices.items()}

# ============================================================
# 3. KHỞI TẠO FACE DETECTOR
# ============================================================

detector = MTCNN()

# ============================================================
# 4. ĐƯỜNG DẪN ẢNH TEST
# ============================================================

# Đổi thành ảnh muốn test
image_path = "/content/vĩ_1.jpg"

# ============================================================
# 5. ĐỌC ẢNH
# ============================================================

image = cv2.imread(image_path)

if image is None:
    raise Exception("Không đọc được ảnh!")

rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# ============================================================
# 6. DETECT FACE
# ============================================================

results = detector.detect_faces(rgb)

if len(results) == 0:

    print("Không phát hiện khuôn mặt!")

else:

    # ========================================================
    # LẤY KHUÔN MẶT ĐẦU TIÊN
    # ========================================================

    x, y, w, h = results[0]['box']

    x = max(0, x)
    y = max(0, y)

    face = rgb[y:y+h, x:x+w]

    # ========================================================
    # RESIZE
    # ========================================================

    face = cv2.resize(face, (160,160))

    # ========================================================
    # CHUẨN HÓA
    # ========================================================

    face = face.astype("float") / 255.0

    face = img_to_array(face)

    face = np.expand_dims(face, axis=0)

    # ========================================================
    # PREDICT
    # ========================================================

    prediction = model.predict(face)

    predicted_class = np.argmax(prediction)

    confidence = np.max(prediction)

    person_name = labels[predicted_class]


    # HIỂN THỊ KẾT QUẢ

    print("======================================")
    print("KẾT QUẢ NHẬN DIỆN")
    print("======================================")

    print("Người dự đoán:", person_name)

    print("Độ tin cậy:", round(confidence * 100, 2), "%")

    # ========================================================
    # VẼ KHUNG KHUÔN MẶT
    # ========================================================

    cv2.rectangle(
        rgb,
        (x,y),
        (x+w,y+h),
        (0,255,0),
        3
    )

    cv2.putText(
        rgb,
        f"{person_name} ({round(confidence*100,2)}%)",
        (x,y-10),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.8,
        (0,255,0),
        2
    )

    # ========================================================
    # HIỂN THỊ ẢNH
    # ========================================================

    plt.figure(figsize=(8,8))

    plt.imshow(rgb)

    plt.axis("off")

    plt.show()